version: '3.8'

services:
  db:
    image: postgres:15
    container_name: university-db
    environment:
      POSTGRES_DB: liquibase_university
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2212
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: university-adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  pgdata:
